### PR TITLE
Update rest-client per https://github.com/rest-client/rest-client/issues/369

### PR DESCRIPTION
**Pull request by sbleon**

### CODE REVIEW

**Comment by sbleon** [comment]
@jsmestad It would be great if you could release a 0.5.13 version with this change, since rest-client is known to be vulnerable to various attacks. I suggest making an 0.5.x branch for that.

**Comment by jsmestad** [comment]
@sbleon will do! thanks

**Comment by jsmestad** [comment]
@sbleon released 0.5.13

**Comment by sbleon** [comment]
Thanks, @jsmestad! You rock!

**Pull request merged**
