### PR TITLE
Story.find only returns nil for 404

### LINKED ISSUE #111: PivotalTracker::Story.find does not differentiate between 404 and other errors
story.rb has:

```ruby
      def find(param, project_id)
        begin
          story = parse(Client.connection["/projects/#{project_id}/stories/#{param}"].get)
          story.project_id = project_id
        rescue RestClient::ExceptionWithResponse
          story = nil
        end
        return story
      end
```

So the caller can't tell whether `nil` is being returned because the story id was not valid (404) or any other error (network issue, invalid token, etc).

The `rescue` clause should re-raise the error unless the response had a 404 status, and only then return `nil`.

### PR DESCRIPTION
**Pull request by afn**
It raises an error for any other error (e.g. 500).

Fixes #111

### CODE REVIEW

**Comment by afn** [comment]
@jsmestad build is failing, but it doesn't appear to be related to this change

**Comment by afn** [comment]
@jsmestad Can this PR be merged?

**Comment by jsmestad** [comment]
@afn sorry was off getting married. Merged

**Comment by afn** [comment]
Congratulations! :confetti_ball: :)

**Comment by sbleon** [comment]
Congratulations, @jsmestad !

**Comment by afn** [comment]
Would you mind pushing a new version to rubygems as well?  Thanks again!

**Comment by afn** [comment]
Happy 2017! :) Could you please push a new version of the gem to rubygems? Thanks!

**Comment by jsmestad** [comment]
Later than 0.5.13? I believe @jasonnoble is prepping for a v5 API version of pivotal_tracker.

**Comment by afn** [comment]
Yes - 0.5.13 was merged in March 2015, and this bugfix was merged in October 2015. If you wouldn't mind pushing 0.5.14 I'd much appreciate it. Thanks!

**Pull request merged**
